/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/96Ceq2u9Nkc
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function reviewcomponentnew() {
  return (
    <Card className="w-full max-w-xs bg-black">
      <CardHeader className="p-4 flex items-center justify-center">
        <div className="grid gap-1.5">
          <CardTitle className="text-base text-white">Stealth</CardTitle>
        </div>
      </CardHeader>
      <img alt="Stealth Image" className="w-full h-40 object-cover" src="/placeholder.svg" />
      <CardContent className="p-4 flex items-center justify-center">
        <div className="grid gap-2 text-2xs">
          <div className="grid grid-cols-5 items-center gap-1.5 text-white justify-center">
            <Avatar className="w-6 h-6 border">
              <AvatarImage alt="Logo" src="/placeholder-logo.jpg" />
              <AvatarFallback>Logo</AvatarFallback>
            </Avatar>
            <div className="flex items-center gap-1.5">
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
            </div>
          </div>
          <div className="grid grid-cols-5 items-center gap-1.5 text-white justify-center">
            <Avatar className="w-6 h-6 border">
              <AvatarImage alt="Logo" src="/placeholder-logo.jpg" />
              <AvatarFallback>Logo</AvatarFallback>
            </Avatar>
            <div className="flex items-center gap-1.5">
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
              <StarIcon className="fill-gray-100 text-sm dark:fill-gray-800" />
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
